export const core_skills = [
	{ title: 'HTML', color: '#e34c26' },
	{ title: 'CSS', color: '#264de4' },
	{ title: 'SCSS', color: '#cc6699' },
	{ title: 'Javascript', color: '#c0ae3e' },
	{ title: 'Typescript', color: '#007acc' },
	{ title: 'ReactJS', color: '#4b9eb3' },
	{ title: 'NextJS', color: 'black' },
	{ title: 'React Query(Tanstack)', color: '#FD8A8A' },
	{ title: 'Redux', color: '#764abc' },
	{ title: 'Redux-toolkit', color: '#764abc' },
	{ title: 'Zustand', color: '#333333' },
	{ title: 'Tailwind', color: '#DC2626' },
	{ title: 'Framer-motion', color: '#0055FF' },
]
